apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
    name: "HTTP"
  - port: 443
    targetPort: 443
    name: "HTTPS"
  selector:
    app: guestbook-ui
